window.AUDIO_PACKS = {
  "zoom": {
    "label": "Zoom · 活力男声",
    "files": {
      "Mike Black": "audio/kokoro/zoom/u01-person-001.wav",
      "Sarah Miller": "audio/kokoro/zoom/u01-person-002.wav",
      "John Baker": "audio/kokoro/zoom/u01-person-003.wav",
      "Chen Jie": "audio/kokoro/zoom/u01-person-004.wav",
      "Wu Binbin": "audio/kokoro/zoom/u01-person-005.wav",
      "Miss White": "audio/kokoro/zoom/u01-person-006.wav",
      "Mr Jones": "audio/kokoro/zoom/u01-person-007.wav",
      "Zoom": "audio/kokoro/zoom/u01-person-008.wav",
      "Zip": "audio/kokoro/zoom/u01-person-009.wav",
      "hello": "audio/kokoro/zoom/u01-word-001.wav",
      "hi": "audio/kokoro/zoom/u01-word-002.wav",
      "name": "audio/kokoro/zoom/u01-word-003.wav",
      "friend": "audio/kokoro/zoom/u01-word-004.wav",
      "good": "audio/kokoro/zoom/u01-word-005.wav",
      "nice": "audio/kokoro/zoom/u01-word-006.wav",
      "meet": "audio/kokoro/zoom/u01-word-007.wav",
      "arm": "audio/kokoro/zoom/u01-word-008.wav",
      "hand": "audio/kokoro/zoom/u01-word-009.wav",
      "ear": "audio/kokoro/zoom/u01-word-010.wav",
      "eye": "audio/kokoro/zoom/u01-word-011.wav",
      "mouth": "audio/kokoro/zoom/u01-word-012.wav",
      "wave": "audio/kokoro/zoom/u01-word-013.wav",
      "point": "audio/kokoro/zoom/u01-word-014.wav",
      "look": "audio/kokoro/zoom/u01-word-015.wav",
      "listen": "audio/kokoro/zoom/u01-word-016.wav",
      "smile": "audio/kokoro/zoom/u01-word-017.wav",
      "share": "audio/kokoro/zoom/u01-word-018.wav",
      "help": "audio/kokoro/zoom/u01-word-019.wav",
      "say": "audio/kokoro/zoom/u01-word-020.wav",
      "play": "audio/kokoro/zoom/u01-word-021.wav",
      "fair": "audio/kokoro/zoom/u01-word-022.wav",
      "care": "audio/kokoro/zoom/u01-word-023.wav",
      "together": "audio/kokoro/zoom/u01-word-024.wav",
      "apple": "audio/kokoro/zoom/u01-word-025.wav",
      "bag": "audio/kokoro/zoom/u01-word-026.wav",
      "bed": "audio/kokoro/zoom/u01-word-027.wav",
      "cat": "audio/kokoro/zoom/u01-word-028.wav",
      "can": "audio/kokoro/zoom/u01-word-029.wav",
      "dad": "audio/kokoro/zoom/u01-word-030.wav",
      "dog": "audio/kokoro/zoom/u01-word-031.wav",
      "What's your name?": "audio/kokoro/zoom/u01-sentence-001.wav",
      "Hello! I'm Mike Black.": "audio/kokoro/zoom/u01-sentence-002.wav",
      "Hi! My name is Wu Binbin.": "audio/kokoro/zoom/u01-sentence-003.wav",
      "Nice to meet you.": "audio/kokoro/zoom/u01-sentence-004.wav",
      "Nice to meet you too.": "audio/kokoro/zoom/u01-sentence-005.wav",
      "We can share.": "audio/kokoro/zoom/u01-sentence-006.wav",
      "It's OK, Chen Jie.": "audio/kokoro/zoom/u01-sentence-007.wav",
      "I listen and say \"Hi!\"": "audio/kokoro/zoom/u01-sentence-008.wav",
      "I help and share.": "audio/kokoro/zoom/u01-sentence-009.wav",
      "We are good friends now.": "audio/kokoro/zoom/u01-sentence-010.wav",
      "Li Na": "audio/kokoro/zoom/u02-person-003.wav",
      "family": "audio/kokoro/zoom/u02-word-001.wav",
      "father": "audio/kokoro/zoom/u02-word-002.wav",
      "mother": "audio/kokoro/zoom/u02-word-004.wav",
      "mum": "audio/kokoro/zoom/u02-word-005.wav",
      "grandfather": "audio/kokoro/zoom/u02-word-006.wav",
      "grandpa": "audio/kokoro/zoom/u02-word-007.wav",
      "grandmother": "audio/kokoro/zoom/u02-word-008.wav",
      "grandma": "audio/kokoro/zoom/u02-word-009.wav",
      "brother": "audio/kokoro/zoom/u02-word-010.wav",
      "sister": "audio/kokoro/zoom/u02-word-011.wav",
      "baby": "audio/kokoro/zoom/u02-word-012.wav",
      "baby sister": "audio/kokoro/zoom/u02-word-013.wav",
      "cousin": "audio/kokoro/zoom/u02-word-014.wav",
      "uncle": "audio/kokoro/zoom/u02-word-015.wav",
      "aunt": "audio/kokoro/zoom/u02-word-016.wav",
      "me": "audio/kokoro/zoom/u02-word-017.wav",
      "big": "audio/kokoro/zoom/u02-word-018.wav",
      "small": "audio/kokoro/zoom/u02-word-019.wav",
      "love": "audio/kokoro/zoom/u02-word-020.wav",
      "live": "audio/kokoro/zoom/u02-word-021.wav",
      "each other": "audio/kokoro/zoom/u02-word-022.wav",
      "egg": "audio/kokoro/zoom/u02-word-023.wav",
      "fish": "audio/kokoro/zoom/u02-word-024.wav",
      "girl": "audio/kokoro/zoom/u02-word-025.wav",
      "pig": "audio/kokoro/zoom/u02-word-026.wav",
      "This is my family.": "audio/kokoro/zoom/u02-sentence-001.wav",
      "This is my mum.": "audio/kokoro/zoom/u02-sentence-002.wav",
      "This is my grandpa.": "audio/kokoro/zoom/u02-sentence-003.wav",
      "Is this your brother?": "audio/kokoro/zoom/u02-sentence-005.wav",
      "Yes, it is.": "audio/kokoro/zoom/u02-sentence-006.wav",
      "No, it's my cousin.": "audio/kokoro/zoom/u02-sentence-007.wav",
      "I have a brother and a baby sister.": "audio/kokoro/zoom/u02-sentence-008.wav",
      "I have two cousins too.": "audio/kokoro/zoom/u02-sentence-009.wav",
      "They love each other.": "audio/kokoro/zoom/u02-sentence-010.wav",
      "Guo Wei": "audio/kokoro/zoom/u03-person-004.wav",
      "animal": "audio/kokoro/zoom/u03-word-001.wav",
      "pet": "audio/kokoro/zoom/u03-word-002.wav",
      "bird": "audio/kokoro/zoom/u03-word-006.wav",
      "rabbit": "audio/kokoro/zoom/u03-word-007.wav",
      "fox": "audio/kokoro/zoom/u03-word-008.wav",
      "red panda": "audio/kokoro/zoom/u03-word-009.wav",
      "panda": "audio/kokoro/zoom/u03-word-010.wav",
      "monkey": "audio/kokoro/zoom/u03-word-011.wav",
      "tiger": "audio/kokoro/zoom/u03-word-012.wav",
      "lion": "audio/kokoro/zoom/u03-word-013.wav",
      "elephant": "audio/kokoro/zoom/u03-word-014.wav",
      "giraffe": "audio/kokoro/zoom/u03-word-015.wav",
      "wild": "audio/kokoro/zoom/u03-word-016.wav",
      "cute": "audio/kokoro/zoom/u03-word-017.wav",
      "tall": "audio/kokoro/zoom/u03-word-020.wav",
      "fast": "audio/kokoro/zoom/u03-word-021.wav",
      "swim": "audio/kokoro/zoom/u03-word-022.wav",
      "hop": "audio/kokoro/zoom/u03-word-023.wav",
      "sing": "audio/kokoro/zoom/u03-word-024.wav",
      "sleep": "audio/kokoro/zoom/u03-word-025.wav",
      "run": "audio/kokoro/zoom/u03-word-026.wav",
      "eat": "audio/kokoro/zoom/u03-word-027.wav",
      "ill": "audio/kokoro/zoom/u03-word-028.wav",
      "kid": "audio/kokoro/zoom/u03-word-029.wav",
      "jet": "audio/kokoro/zoom/u03-word-030.wav",
      "kite": "audio/kokoro/zoom/u03-word-031.wav",
      "Do you have a pet?": "audio/kokoro/zoom/u03-sentence-001.wav",
      "Yes, I do. I have a dog.": "audio/kokoro/zoom/u03-sentence-002.wav",
      "No, I don't.": "audio/kokoro/zoom/u03-sentence-003.wav",
      "I like your dog.": "audio/kokoro/zoom/u03-sentence-004.wav",
      "I like fish.": "audio/kokoro/zoom/u03-sentence-005.wav",
      "What's this?": "audio/kokoro/zoom/u03-sentence-006.wav",
      "What's that?": "audio/kokoro/zoom/u03-sentence-007.wav",
      "It's a fox.": "audio/kokoro/zoom/u03-sentence-008.wav",
      "It's a red panda.": "audio/kokoro/zoom/u03-sentence-009.wav",
      "Let's go to the zoo!": "audio/kokoro/zoom/u03-sentence-010.wav",
      "The elephant is big.": "audio/kokoro/zoom/u03-sentence-011.wav",
      "The giraffe is tall.": "audio/kokoro/zoom/u03-sentence-012.wav",
      "The lion is fast.": "audio/kokoro/zoom/u03-sentence-013.wav",
      "plant": "audio/kokoro/zoom/u04-word-001.wav",
      "fruit": "audio/kokoro/zoom/u04-word-002.wav",
      "banana": "audio/kokoro/zoom/u04-word-004.wav",
      "grape": "audio/kokoro/zoom/u04-word-005.wav",
      "orange": "audio/kokoro/zoom/u04-word-006.wav",
      "farm": "audio/kokoro/zoom/u04-word-007.wav",
      "garden": "audio/kokoro/zoom/u04-word-008.wav",
      "tree": "audio/kokoro/zoom/u04-word-009.wav",
      "flower": "audio/kokoro/zoom/u04-word-010.wav",
      "grass": "audio/kokoro/zoom/u04-word-011.wav",
      "leaf": "audio/kokoro/zoom/u04-word-012.wav",
      "air": "audio/kokoro/zoom/u04-word-013.wav",
      "water": "audio/kokoro/zoom/u04-word-014.wav",
      "sun": "audio/kokoro/zoom/u04-word-015.wav",
      "spring": "audio/kokoro/zoom/u04-word-016.wav",
      "fresh": "audio/kokoro/zoom/u04-word-017.wav",
      "strong": "audio/kokoro/zoom/u04-word-018.wav",
      "long": "audio/kokoro/zoom/u04-word-019.wav",
      "grow": "audio/kokoro/zoom/u04-word-020.wav",
      "give": "audio/kokoro/zoom/u04-word-021.wav",
      "need": "audio/kokoro/zoom/u04-word-022.wav",
      "cut": "audio/kokoro/zoom/u04-word-023.wav",
      "turn": "audio/kokoro/zoom/u04-word-024.wav",
      "new": "audio/kokoro/zoom/u04-word-025.wav",
      "map": "audio/kokoro/zoom/u04-word-026.wav",
      "fan": "audio/kokoro/zoom/u04-word-027.wav",
      "Do you like the farm?": "audio/kokoro/zoom/u04-sentence-001.wav",
      "Mike, do you like apples?": "audio/kokoro/zoom/u04-sentence-002.wav",
      "Yes, I do. And you?": "audio/kokoro/zoom/u04-sentence-003.wav",
      "No, I don't. I like bananas.": "audio/kokoro/zoom/u04-sentence-004.wav",
      "I like the fresh air.": "audio/kokoro/zoom/u04-sentence-005.wav",
      "Grapes are small. Bananas are long.": "audio/kokoro/zoom/u04-sentence-006.wav",
      "We can plant new trees.": "audio/kokoro/zoom/u04-sentence-007.wav",
      "We can water the flowers.": "audio/kokoro/zoom/u04-sentence-008.wav",
      "Plants need air, water and sun.": "audio/kokoro/zoom/u04-sentence-009.wav",
      "Plants can give us many things.": "audio/kokoro/zoom/u04-sentence-010.wav",
      "colour": "audio/kokoro/zoom/u05-word-001.wav",
      "red": "audio/kokoro/zoom/u05-word-002.wav",
      "yellow": "audio/kokoro/zoom/u05-word-004.wav",
      "green": "audio/kokoro/zoom/u05-word-005.wav",
      "blue": "audio/kokoro/zoom/u05-word-006.wav",
      "purple": "audio/kokoro/zoom/u05-word-007.wav",
      "brown": "audio/kokoro/zoom/u05-word-008.wav",
      "black": "audio/kokoro/zoom/u05-word-009.wav",
      "white": "audio/kokoro/zoom/u05-word-010.wav",
      "pink": "audio/kokoro/zoom/u05-word-011.wav",
      "snow": "audio/kokoro/zoom/u05-word-012.wav",
      "rose": "audio/kokoro/zoom/u05-word-013.wav",
      "sky": "audio/kokoro/zoom/u05-word-014.wav",
      "sea": "audio/kokoro/zoom/u05-word-015.wav",
      "bear": "audio/kokoro/zoom/u05-word-018.wav",
      "duck": "audio/kokoro/zoom/u05-word-019.wav",
      "rainbow": "audio/kokoro/zoom/u05-word-022.wav",
      "sunflower": "audio/kokoro/zoom/u05-word-023.wav",
      "bee": "audio/kokoro/zoom/u05-word-024.wav",
      "make": "audio/kokoro/zoom/u05-word-025.wav",
      "draw": "audio/kokoro/zoom/u05-word-026.wav",
      "touch": "audio/kokoro/zoom/u05-word-027.wav",
      "jump": "audio/kokoro/zoom/u05-word-028.wav",
      "sit": "audio/kokoro/zoom/u05-word-029.wav",
      "careful": "audio/kokoro/zoom/u05-word-030.wav",
      "use": "audio/kokoro/zoom/u05-word-031.wav",
      "What colours do you see?": "audio/kokoro/zoom/u05-sentence-001.wav",
      "What colour is it?": "audio/kokoro/zoom/u05-sentence-002.wav",
      "It's orange.": "audio/kokoro/zoom/u05-sentence-003.wav",
      "Red and blue make purple.": "audio/kokoro/zoom/u05-sentence-004.wav",
      "Blue and yellow make green.": "audio/kokoro/zoom/u05-sentence-005.wav",
      "What colours do you like?": "audio/kokoro/zoom/u05-sentence-006.wav",
      "I like red and pink.": "audio/kokoro/zoom/u05-sentence-007.wav",
      "It's green. Green can say 'Go!'": "audio/kokoro/zoom/u05-sentence-008.wav",
      "It's red. Red can say 'No!'": "audio/kokoro/zoom/u05-sentence-009.wav",
      "It's yellow. Yellow can say 'Be careful!'": "audio/kokoro/zoom/u05-sentence-010.wav",
      "It's blue. Blue can say 'Use again!'": "audio/kokoro/zoom/u05-sentence-011.wav",
      "I am a sunflower.": "audio/kokoro/zoom/u05-sentence-012.wav",
      "Sam": "audio/kokoro/zoom/u06-person-002.wav",
      "Xinxin": "audio/kokoro/zoom/u06-person-003.wav",
      "Xiaoli": "audio/kokoro/zoom/u06-person-004.wav",
      "Feifei": "audio/kokoro/zoom/u06-person-005.wav",
      "Matt": "audio/kokoro/zoom/u06-person-006.wav",
      "number": "audio/kokoro/zoom/u06-word-001.wav",
      "one": "audio/kokoro/zoom/u06-word-002.wav",
      "two": "audio/kokoro/zoom/u06-word-003.wav",
      "three": "audio/kokoro/zoom/u06-word-004.wav",
      "four": "audio/kokoro/zoom/u06-word-005.wav",
      "five": "audio/kokoro/zoom/u06-word-006.wav",
      "six": "audio/kokoro/zoom/u06-word-007.wav",
      "seven": "audio/kokoro/zoom/u06-word-008.wav",
      "eight": "audio/kokoro/zoom/u06-word-009.wav",
      "nine": "audio/kokoro/zoom/u06-word-010.wav",
      "ten": "audio/kokoro/zoom/u06-word-011.wav",
      "old": "audio/kokoro/zoom/u06-word-012.wav",
      "year": "audio/kokoro/zoom/u06-word-013.wav",
      "yuan": "audio/kokoro/zoom/u06-word-014.wav",
      "o'clock": "audio/kokoro/zoom/u06-word-015.wav",
      "shop": "audio/kokoro/zoom/u06-word-016.wav",
      "odd": "audio/kokoro/zoom/u06-word-017.wav",
      "even": "audio/kokoro/zoom/u06-word-018.wav",
      "spider": "audio/kokoro/zoom/u06-word-020.wav",
      "child": "audio/kokoro/zoom/u06-word-021.wav",
      "head": "audio/kokoro/zoom/u06-word-022.wav",
      "wing": "audio/kokoro/zoom/u06-word-023.wav",
      "leg": "audio/kokoro/zoom/u06-word-024.wav",
      "toe": "audio/kokoro/zoom/u06-word-025.wav",
      "cake": "audio/kokoro/zoom/u06-word-026.wav",
      "birthday": "audio/kokoro/zoom/u06-word-027.wav",
      "card": "audio/kokoro/zoom/u06-word-028.wav",
      "party": "audio/kokoro/zoom/u06-word-029.wav",
      "time": "audio/kokoro/zoom/u06-word-030.wav",
      "hurry": "audio/kokoro/zoom/u06-word-031.wav",
      "more": "audio/kokoro/zoom/u06-word-032.wav",
      "How old are you?": "audio/kokoro/zoom/u06-sentence-001.wav",
      "I'm five years old.": "audio/kokoro/zoom/u06-sentence-002.wav",
      "Me too.": "audio/kokoro/zoom/u06-sentence-003.wav",
      "How many apples?": "audio/kokoro/zoom/u06-sentence-004.wav",
      "Two.": "audio/kokoro/zoom/u06-sentence-005.wav",
      "Three. And one orange.": "audio/kokoro/zoom/u06-sentence-006.wav",
      "I have ten yuan.": "audio/kokoro/zoom/u06-sentence-007.wav",
      "Let's go to the shop!": "audio/kokoro/zoom/u06-sentence-008.wav",
      "That's ten yuan, please.": "audio/kokoro/zoom/u06-sentence-009.wav",
      "Here you are.": "audio/kokoro/zoom/u06-sentence-010.wav",
      "Happy birthday!": "audio/kokoro/zoom/u06-sentence-011.wav",
      "It's seven o'clock. Hurry!": "audio/kokoro/zoom/u06-sentence-012.wav",
      "Oh, one more cut for the dog.": "audio/kokoro/zoom/u06-sentence-013.wav",
      "Dogs don't eat cake, Sam!": "audio/kokoro/zoom/u06-sentence-014.wav",
      "guest": "audio/kokoro/zoom/u07-word-001.wav",
      "polite": "audio/kokoro/zoom/u07-word-002.wav",
      "knock": "audio/kokoro/zoom/u07-word-006.wav",
      "toy": "audio/kokoro/zoom/u07-word-007.wav",
      "goodbye": "audio/kokoro/zoom/u07-word-009.wav",
      "please": "audio/kokoro/zoom/u07-word-010.wav",
      "thank you": "audio/kokoro/zoom/u07-word-011.wav",
      "quiet": "audio/kokoro/zoom/u07-word-012.wav",
      "ask": "audio/kokoro/zoom/u07-word-015.wav",
      "show": "audio/kokoro/zoom/u07-word-016.wav",
      "Good morning! Come in.": "audio/kokoro/zoom/u07-sentence-001.wav",
      "Mum! Dad! This is Wu Binbin.": "audio/kokoro/zoom/u07-sentence-002.wav",
      "This is for you.": "audio/kokoro/zoom/u07-sentence-004.wav",
      "Thank you.": "audio/kokoro/zoom/u07-sentence-005.wav",
      "Do you like bananas, Binbin?": "audio/kokoro/zoom/u07-sentence-006.wav",
      "Yes, I do. Thanks.": "audio/kokoro/zoom/u07-sentence-007.wav",
      "Be a good guest. Be polite!": "audio/kokoro/zoom/u07-sentence-008.wav",
      "Share your toys and listen with care.": "audio/kokoro/zoom/u07-sentence-009.wav",
      "Let's play together!": "audio/kokoro/zoom/u07-sentence-010.wav",
      "Say \"Goodbye!\"": "audio/kokoro/zoom/u07-sentence-011.wav"
    }
  },
  "sarah": {
    "label": "Sarah · 自然女声",
    "files": {
      "Mike Black": "audio/kokoro/sarah/u01-person-001.wav",
      "Sarah Miller": "audio/kokoro/sarah/u01-person-002.wav",
      "John Baker": "audio/kokoro/sarah/u01-person-003.wav",
      "Chen Jie": "audio/kokoro/sarah/u01-person-004.wav",
      "Wu Binbin": "audio/kokoro/sarah/u01-person-005.wav",
      "Miss White": "audio/kokoro/sarah/u01-person-006.wav",
      "Mr Jones": "audio/kokoro/sarah/u01-person-007.wav",
      "Zoom": "audio/kokoro/sarah/u01-person-008.wav",
      "Zip": "audio/kokoro/sarah/u01-person-009.wav",
      "hello": "audio/kokoro/sarah/u01-word-001.wav",
      "hi": "audio/kokoro/sarah/u01-word-002.wav",
      "name": "audio/kokoro/sarah/u01-word-003.wav",
      "friend": "audio/kokoro/sarah/u01-word-004.wav",
      "good": "audio/kokoro/sarah/u01-word-005.wav",
      "nice": "audio/kokoro/sarah/u01-word-006.wav",
      "meet": "audio/kokoro/sarah/u01-word-007.wav",
      "arm": "audio/kokoro/sarah/u01-word-008.wav",
      "hand": "audio/kokoro/sarah/u01-word-009.wav",
      "ear": "audio/kokoro/sarah/u01-word-010.wav",
      "eye": "audio/kokoro/sarah/u01-word-011.wav",
      "mouth": "audio/kokoro/sarah/u01-word-012.wav",
      "wave": "audio/kokoro/sarah/u01-word-013.wav",
      "point": "audio/kokoro/sarah/u01-word-014.wav",
      "look": "audio/kokoro/sarah/u01-word-015.wav",
      "listen": "audio/kokoro/sarah/u01-word-016.wav",
      "smile": "audio/kokoro/sarah/u01-word-017.wav",
      "share": "audio/kokoro/sarah/u01-word-018.wav",
      "help": "audio/kokoro/sarah/u01-word-019.wav",
      "say": "audio/kokoro/sarah/u01-word-020.wav",
      "play": "audio/kokoro/sarah/u01-word-021.wav",
      "fair": "audio/kokoro/sarah/u01-word-022.wav",
      "care": "audio/kokoro/sarah/u01-word-023.wav",
      "together": "audio/kokoro/sarah/u01-word-024.wav",
      "apple": "audio/kokoro/sarah/u01-word-025.wav",
      "bag": "audio/kokoro/sarah/u01-word-026.wav",
      "bed": "audio/kokoro/sarah/u01-word-027.wav",
      "cat": "audio/kokoro/sarah/u01-word-028.wav",
      "can": "audio/kokoro/sarah/u01-word-029.wav",
      "dad": "audio/kokoro/sarah/u01-word-030.wav",
      "dog": "audio/kokoro/sarah/u01-word-031.wav",
      "What's your name?": "audio/kokoro/sarah/u01-sentence-001.wav",
      "Hello! I'm Mike Black.": "audio/kokoro/sarah/u01-sentence-002.wav",
      "Hi! My name is Wu Binbin.": "audio/kokoro/sarah/u01-sentence-003.wav",
      "Nice to meet you.": "audio/kokoro/sarah/u01-sentence-004.wav",
      "Nice to meet you too.": "audio/kokoro/sarah/u01-sentence-005.wav",
      "We can share.": "audio/kokoro/sarah/u01-sentence-006.wav",
      "It's OK, Chen Jie.": "audio/kokoro/sarah/u01-sentence-007.wav",
      "I listen and say \"Hi!\"": "audio/kokoro/sarah/u01-sentence-008.wav",
      "I help and share.": "audio/kokoro/sarah/u01-sentence-009.wav",
      "We are good friends now.": "audio/kokoro/sarah/u01-sentence-010.wav",
      "Li Na": "audio/kokoro/sarah/u02-person-003.wav",
      "family": "audio/kokoro/sarah/u02-word-001.wav",
      "father": "audio/kokoro/sarah/u02-word-002.wav",
      "mother": "audio/kokoro/sarah/u02-word-004.wav",
      "mum": "audio/kokoro/sarah/u02-word-005.wav",
      "grandfather": "audio/kokoro/sarah/u02-word-006.wav",
      "grandpa": "audio/kokoro/sarah/u02-word-007.wav",
      "grandmother": "audio/kokoro/sarah/u02-word-008.wav",
      "grandma": "audio/kokoro/sarah/u02-word-009.wav",
      "brother": "audio/kokoro/sarah/u02-word-010.wav",
      "sister": "audio/kokoro/sarah/u02-word-011.wav",
      "baby": "audio/kokoro/sarah/u02-word-012.wav",
      "baby sister": "audio/kokoro/sarah/u02-word-013.wav",
      "cousin": "audio/kokoro/sarah/u02-word-014.wav",
      "uncle": "audio/kokoro/sarah/u02-word-015.wav",
      "aunt": "audio/kokoro/sarah/u02-word-016.wav",
      "me": "audio/kokoro/sarah/u02-word-017.wav",
      "big": "audio/kokoro/sarah/u02-word-018.wav",
      "small": "audio/kokoro/sarah/u02-word-019.wav",
      "love": "audio/kokoro/sarah/u02-word-020.wav",
      "live": "audio/kokoro/sarah/u02-word-021.wav",
      "each other": "audio/kokoro/sarah/u02-word-022.wav",
      "egg": "audio/kokoro/sarah/u02-word-023.wav",
      "fish": "audio/kokoro/sarah/u02-word-024.wav",
      "girl": "audio/kokoro/sarah/u02-word-025.wav",
      "pig": "audio/kokoro/sarah/u02-word-026.wav",
      "This is my family.": "audio/kokoro/sarah/u02-sentence-001.wav",
      "This is my mum.": "audio/kokoro/sarah/u02-sentence-002.wav",
      "This is my grandpa.": "audio/kokoro/sarah/u02-sentence-003.wav",
      "Is this your brother?": "audio/kokoro/sarah/u02-sentence-005.wav",
      "Yes, it is.": "audio/kokoro/sarah/u02-sentence-006.wav",
      "No, it's my cousin.": "audio/kokoro/sarah/u02-sentence-007.wav",
      "I have a brother and a baby sister.": "audio/kokoro/sarah/u02-sentence-008.wav",
      "I have two cousins too.": "audio/kokoro/sarah/u02-sentence-009.wav",
      "They love each other.": "audio/kokoro/sarah/u02-sentence-010.wav",
      "Guo Wei": "audio/kokoro/sarah/u03-person-004.wav",
      "animal": "audio/kokoro/sarah/u03-word-001.wav",
      "pet": "audio/kokoro/sarah/u03-word-002.wav",
      "bird": "audio/kokoro/sarah/u03-word-006.wav",
      "rabbit": "audio/kokoro/sarah/u03-word-007.wav",
      "fox": "audio/kokoro/sarah/u03-word-008.wav",
      "red panda": "audio/kokoro/sarah/u03-word-009.wav",
      "panda": "audio/kokoro/sarah/u03-word-010.wav",
      "monkey": "audio/kokoro/sarah/u03-word-011.wav",
      "tiger": "audio/kokoro/sarah/u03-word-012.wav",
      "lion": "audio/kokoro/sarah/u03-word-013.wav",
      "elephant": "audio/kokoro/sarah/u03-word-014.wav",
      "giraffe": "audio/kokoro/sarah/u03-word-015.wav",
      "wild": "audio/kokoro/sarah/u03-word-016.wav",
      "cute": "audio/kokoro/sarah/u03-word-017.wav",
      "tall": "audio/kokoro/sarah/u03-word-020.wav",
      "fast": "audio/kokoro/sarah/u03-word-021.wav",
      "swim": "audio/kokoro/sarah/u03-word-022.wav",
      "hop": "audio/kokoro/sarah/u03-word-023.wav",
      "sing": "audio/kokoro/sarah/u03-word-024.wav",
      "sleep": "audio/kokoro/sarah/u03-word-025.wav",
      "run": "audio/kokoro/sarah/u03-word-026.wav",
      "eat": "audio/kokoro/sarah/u03-word-027.wav",
      "ill": "audio/kokoro/sarah/u03-word-028.wav",
      "kid": "audio/kokoro/sarah/u03-word-029.wav",
      "jet": "audio/kokoro/sarah/u03-word-030.wav",
      "kite": "audio/kokoro/sarah/u03-word-031.wav",
      "Do you have a pet?": "audio/kokoro/sarah/u03-sentence-001.wav",
      "Yes, I do. I have a dog.": "audio/kokoro/sarah/u03-sentence-002.wav",
      "No, I don't.": "audio/kokoro/sarah/u03-sentence-003.wav",
      "I like your dog.": "audio/kokoro/sarah/u03-sentence-004.wav",
      "I like fish.": "audio/kokoro/sarah/u03-sentence-005.wav",
      "What's this?": "audio/kokoro/sarah/u03-sentence-006.wav",
      "What's that?": "audio/kokoro/sarah/u03-sentence-007.wav",
      "It's a fox.": "audio/kokoro/sarah/u03-sentence-008.wav",
      "It's a red panda.": "audio/kokoro/sarah/u03-sentence-009.wav",
      "Let's go to the zoo!": "audio/kokoro/sarah/u03-sentence-010.wav",
      "The elephant is big.": "audio/kokoro/sarah/u03-sentence-011.wav",
      "The giraffe is tall.": "audio/kokoro/sarah/u03-sentence-012.wav",
      "The lion is fast.": "audio/kokoro/sarah/u03-sentence-013.wav",
      "plant": "audio/kokoro/sarah/u04-word-001.wav",
      "fruit": "audio/kokoro/sarah/u04-word-002.wav",
      "banana": "audio/kokoro/sarah/u04-word-004.wav",
      "grape": "audio/kokoro/sarah/u04-word-005.wav",
      "orange": "audio/kokoro/sarah/u04-word-006.wav",
      "farm": "audio/kokoro/sarah/u04-word-007.wav",
      "garden": "audio/kokoro/sarah/u04-word-008.wav",
      "tree": "audio/kokoro/sarah/u04-word-009.wav",
      "flower": "audio/kokoro/sarah/u04-word-010.wav",
      "grass": "audio/kokoro/sarah/u04-word-011.wav",
      "leaf": "audio/kokoro/sarah/u04-word-012.wav",
      "air": "audio/kokoro/sarah/u04-word-013.wav",
      "water": "audio/kokoro/sarah/u04-word-014.wav",
      "sun": "audio/kokoro/sarah/u04-word-015.wav",
      "spring": "audio/kokoro/sarah/u04-word-016.wav",
      "fresh": "audio/kokoro/sarah/u04-word-017.wav",
      "strong": "audio/kokoro/sarah/u04-word-018.wav",
      "long": "audio/kokoro/sarah/u04-word-019.wav",
      "grow": "audio/kokoro/sarah/u04-word-020.wav",
      "give": "audio/kokoro/sarah/u04-word-021.wav",
      "need": "audio/kokoro/sarah/u04-word-022.wav",
      "cut": "audio/kokoro/sarah/u04-word-023.wav",
      "turn": "audio/kokoro/sarah/u04-word-024.wav",
      "new": "audio/kokoro/sarah/u04-word-025.wav",
      "map": "audio/kokoro/sarah/u04-word-026.wav",
      "fan": "audio/kokoro/sarah/u04-word-027.wav",
      "Do you like the farm?": "audio/kokoro/sarah/u04-sentence-001.wav",
      "Mike, do you like apples?": "audio/kokoro/sarah/u04-sentence-002.wav",
      "Yes, I do. And you?": "audio/kokoro/sarah/u04-sentence-003.wav",
      "No, I don't. I like bananas.": "audio/kokoro/sarah/u04-sentence-004.wav",
      "I like the fresh air.": "audio/kokoro/sarah/u04-sentence-005.wav",
      "Grapes are small. Bananas are long.": "audio/kokoro/sarah/u04-sentence-006.wav",
      "We can plant new trees.": "audio/kokoro/sarah/u04-sentence-007.wav",
      "We can water the flowers.": "audio/kokoro/sarah/u04-sentence-008.wav",
      "Plants need air, water and sun.": "audio/kokoro/sarah/u04-sentence-009.wav",
      "Plants can give us many things.": "audio/kokoro/sarah/u04-sentence-010.wav",
      "colour": "audio/kokoro/sarah/u05-word-001.wav",
      "red": "audio/kokoro/sarah/u05-word-002.wav",
      "yellow": "audio/kokoro/sarah/u05-word-004.wav",
      "green": "audio/kokoro/sarah/u05-word-005.wav",
      "blue": "audio/kokoro/sarah/u05-word-006.wav",
      "purple": "audio/kokoro/sarah/u05-word-007.wav",
      "brown": "audio/kokoro/sarah/u05-word-008.wav",
      "black": "audio/kokoro/sarah/u05-word-009.wav",
      "white": "audio/kokoro/sarah/u05-word-010.wav",
      "pink": "audio/kokoro/sarah/u05-word-011.wav",
      "snow": "audio/kokoro/sarah/u05-word-012.wav",
      "rose": "audio/kokoro/sarah/u05-word-013.wav",
      "sky": "audio/kokoro/sarah/u05-word-014.wav",
      "sea": "audio/kokoro/sarah/u05-word-015.wav",
      "bear": "audio/kokoro/sarah/u05-word-018.wav",
      "duck": "audio/kokoro/sarah/u05-word-019.wav",
      "rainbow": "audio/kokoro/sarah/u05-word-022.wav",
      "sunflower": "audio/kokoro/sarah/u05-word-023.wav",
      "bee": "audio/kokoro/sarah/u05-word-024.wav",
      "make": "audio/kokoro/sarah/u05-word-025.wav",
      "draw": "audio/kokoro/sarah/u05-word-026.wav",
      "touch": "audio/kokoro/sarah/u05-word-027.wav",
      "jump": "audio/kokoro/sarah/u05-word-028.wav",
      "sit": "audio/kokoro/sarah/u05-word-029.wav",
      "careful": "audio/kokoro/sarah/u05-word-030.wav",
      "use": "audio/kokoro/sarah/u05-word-031.wav",
      "What colours do you see?": "audio/kokoro/sarah/u05-sentence-001.wav",
      "What colour is it?": "audio/kokoro/sarah/u05-sentence-002.wav",
      "It's orange.": "audio/kokoro/sarah/u05-sentence-003.wav",
      "Red and blue make purple.": "audio/kokoro/sarah/u05-sentence-004.wav",
      "Blue and yellow make green.": "audio/kokoro/sarah/u05-sentence-005.wav",
      "What colours do you like?": "audio/kokoro/sarah/u05-sentence-006.wav",
      "I like red and pink.": "audio/kokoro/sarah/u05-sentence-007.wav",
      "It's green. Green can say 'Go!'": "audio/kokoro/sarah/u05-sentence-008.wav",
      "It's red. Red can say 'No!'": "audio/kokoro/sarah/u05-sentence-009.wav",
      "It's yellow. Yellow can say 'Be careful!'": "audio/kokoro/sarah/u05-sentence-010.wav",
      "It's blue. Blue can say 'Use again!'": "audio/kokoro/sarah/u05-sentence-011.wav",
      "I am a sunflower.": "audio/kokoro/sarah/u05-sentence-012.wav",
      "Sam": "audio/kokoro/sarah/u06-person-002.wav",
      "Xinxin": "audio/kokoro/sarah/u06-person-003.wav",
      "Xiaoli": "audio/kokoro/sarah/u06-person-004.wav",
      "Feifei": "audio/kokoro/sarah/u06-person-005.wav",
      "Matt": "audio/kokoro/sarah/u06-person-006.wav",
      "number": "audio/kokoro/sarah/u06-word-001.wav",
      "one": "audio/kokoro/sarah/u06-word-002.wav",
      "two": "audio/kokoro/sarah/u06-word-003.wav",
      "three": "audio/kokoro/sarah/u06-word-004.wav",
      "four": "audio/kokoro/sarah/u06-word-005.wav",
      "five": "audio/kokoro/sarah/u06-word-006.wav",
      "six": "audio/kokoro/sarah/u06-word-007.wav",
      "seven": "audio/kokoro/sarah/u06-word-008.wav",
      "eight": "audio/kokoro/sarah/u06-word-009.wav",
      "nine": "audio/kokoro/sarah/u06-word-010.wav",
      "ten": "audio/kokoro/sarah/u06-word-011.wav",
      "old": "audio/kokoro/sarah/u06-word-012.wav",
      "year": "audio/kokoro/sarah/u06-word-013.wav",
      "yuan": "audio/kokoro/sarah/u06-word-014.wav",
      "o'clock": "audio/kokoro/sarah/u06-word-015.wav",
      "shop": "audio/kokoro/sarah/u06-word-016.wav",
      "odd": "audio/kokoro/sarah/u06-word-017.wav",
      "even": "audio/kokoro/sarah/u06-word-018.wav",
      "spider": "audio/kokoro/sarah/u06-word-020.wav",
      "child": "audio/kokoro/sarah/u06-word-021.wav",
      "head": "audio/kokoro/sarah/u06-word-022.wav",
      "wing": "audio/kokoro/sarah/u06-word-023.wav",
      "leg": "audio/kokoro/sarah/u06-word-024.wav",
      "toe": "audio/kokoro/sarah/u06-word-025.wav",
      "cake": "audio/kokoro/sarah/u06-word-026.wav",
      "birthday": "audio/kokoro/sarah/u06-word-027.wav",
      "card": "audio/kokoro/sarah/u06-word-028.wav",
      "party": "audio/kokoro/sarah/u06-word-029.wav",
      "time": "audio/kokoro/sarah/u06-word-030.wav",
      "hurry": "audio/kokoro/sarah/u06-word-031.wav",
      "more": "audio/kokoro/sarah/u06-word-032.wav",
      "How old are you?": "audio/kokoro/sarah/u06-sentence-001.wav",
      "I'm five years old.": "audio/kokoro/sarah/u06-sentence-002.wav",
      "Me too.": "audio/kokoro/sarah/u06-sentence-003.wav",
      "How many apples?": "audio/kokoro/sarah/u06-sentence-004.wav",
      "Two.": "audio/kokoro/sarah/u06-sentence-005.wav",
      "Three. And one orange.": "audio/kokoro/sarah/u06-sentence-006.wav",
      "I have ten yuan.": "audio/kokoro/sarah/u06-sentence-007.wav",
      "Let's go to the shop!": "audio/kokoro/sarah/u06-sentence-008.wav",
      "That's ten yuan, please.": "audio/kokoro/sarah/u06-sentence-009.wav",
      "Here you are.": "audio/kokoro/sarah/u06-sentence-010.wav",
      "Happy birthday!": "audio/kokoro/sarah/u06-sentence-011.wav",
      "It's seven o'clock. Hurry!": "audio/kokoro/sarah/u06-sentence-012.wav",
      "Oh, one more cut for the dog.": "audio/kokoro/sarah/u06-sentence-013.wav",
      "Dogs don't eat cake, Sam!": "audio/kokoro/sarah/u06-sentence-014.wav",
      "guest": "audio/kokoro/sarah/u07-word-001.wav",
      "polite": "audio/kokoro/sarah/u07-word-002.wav",
      "knock": "audio/kokoro/sarah/u07-word-006.wav",
      "toy": "audio/kokoro/sarah/u07-word-007.wav",
      "goodbye": "audio/kokoro/sarah/u07-word-009.wav",
      "please": "audio/kokoro/sarah/u07-word-010.wav",
      "thank you": "audio/kokoro/sarah/u07-word-011.wav",
      "quiet": "audio/kokoro/sarah/u07-word-012.wav",
      "ask": "audio/kokoro/sarah/u07-word-015.wav",
      "show": "audio/kokoro/sarah/u07-word-016.wav",
      "Good morning! Come in.": "audio/kokoro/sarah/u07-sentence-001.wav",
      "Mum! Dad! This is Wu Binbin.": "audio/kokoro/sarah/u07-sentence-002.wav",
      "This is for you.": "audio/kokoro/sarah/u07-sentence-004.wav",
      "Thank you.": "audio/kokoro/sarah/u07-sentence-005.wav",
      "Do you like bananas, Binbin?": "audio/kokoro/sarah/u07-sentence-006.wav",
      "Yes, I do. Thanks.": "audio/kokoro/sarah/u07-sentence-007.wav",
      "Be a good guest. Be polite!": "audio/kokoro/sarah/u07-sentence-008.wav",
      "Share your toys and listen with care.": "audio/kokoro/sarah/u07-sentence-009.wav",
      "Let's play together!": "audio/kokoro/sarah/u07-sentence-010.wav",
      "Say \"Goodbye!\"": "audio/kokoro/sarah/u07-sentence-011.wav"
    }
  }
};
window.AUDIO_FILES = window.AUDIO_PACKS.zoom.files;
